# Generated by Django 3.1.4 on 2020-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0001_initial'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='DatasetPreprocessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clump_thickness', models.FloatField(blank=True, null=True)),
                ('uniformity_of_cell_size', models.FloatField(blank=True, null=True)),
                ('uniformity_of_cell_shape', models.FloatField(blank=True, null=True)),
                ('marginal_adhesion', models.FloatField(blank=True, null=True)),
                ('single_epithelial_cell_size', models.FloatField(blank=True, null=True)),
                ('bare_nuclei', models.FloatField(blank=True, null=True)),
                ('bland_chromatin', models.FloatField(blank=True, null=True)),
                ('normal_nucleoli', models.FloatField(blank=True, null=True)),
                ('mitoses', models.FloatField(blank=True, null=True)),
                ('kelas', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
