# Generated by Django 3.1.4 on 2022-02-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0006_bobotakhir_bobotawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='albumin',
            new_name='bare_nuclei',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='alk_posphate',
            new_name='bland_chromatin',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='age',
            new_name='clump_thickness',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='anorexia',
            new_name='marginal_adhesion',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='antivirals',
            new_name='mitoses',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='ascites',
            new_name='normal_nucleoli',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='bilirubin',
            new_name='single_epithelial_cell_size',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='fatigue',
            new_name='uniformity_of_cell_shape',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='histology',
            new_name='uniformity_of_cell_size',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='liver_big',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='liver_firm',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='malaise',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='protime',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='sgot',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='spiders',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='spleen_palpable',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='steroid',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='varices',
        ),
    ]
